# Generated by Django 5.0.6 on 2024-07-07 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_list', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('date_due', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
    ]
