# Generated by Django 5.0.6 on 2024-07-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.DateField(auto_now_add=True)),
                ('age', models.PositiveIntegerField()),
                ('occupation', models.CharField(max_length=30)),
                ('marital_status', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
