# Generated by Django 5.0.6 on 2024-07-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
    ]
