# Generated by Django 5.0.6 on 2024-07-29 15:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_list',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('date_liked', models.DateTimeField(default=datetime.datetime.now)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='todo.todo')),
            ],
        ),
    ]
