# Generated by Django 5.0.6 on 2024-12-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_alter_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.ImageField(default='cafe.jpg', upload_to=''),
        ),
    ]
