# Generated by Django 5.0.6 on 2024-07-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_alter_comment_todo_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
