# Generated by Django 5.0.6 on 2024-10-03 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_alter_comments_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbsUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbup', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
