# Generated by Django 5.0.6 on 2024-10-04 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_thumbsup'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbsup',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='thumbups', to='comment.comments'),
        ),
    ]
