# Generated by Django 5.0.6 on 2024-10-06 10:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0010_thumbsup_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='thumbup',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(default=datetime.datetime.now)),
                ('comment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='thumbups', to='comment.comments')),
            ],
        ),
        migrations.DeleteModel(
            name='ThumbsUp',
        ),
    ]
