# Generated by Django 5.0.6 on 2024-10-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0011_comments_thumbup_like_delete_thumbsup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='thumbup',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
