# Generated by Django 5.0.6 on 2024-10-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0012_alter_comments_thumbup_delete_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='thumbup',
            new_name='thumbsup',
        ),
    ]
