# Generated by Django 5.0.6 on 2024-10-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0013_rename_thumbup_comments_thumbsup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='thumbsup',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
